# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e7c4d3eead116f17d463d12afb7972fc4589ffd92a42d71f94cd3969f6ee435603a0e6297dfc53bc531f499d54abdf3d7dff0c1d609b6e8ebeef45cafeb43a4

test:
  secret_key_base: 6010b60a3e6ae43c5f6672c00c61f9f238e090ebc914a69a2db117bb684f96bb7308b28b868a1cd86b8075a6efbdb4c82044af086454b6ffeb037af8cc6c0a7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
